# สั่งให้ Netlify มีขั้นตอนการ Build
[build]
  command = "echo 'Applying settings from netlify.toml'"
  functions = "netlify/functions"

# ตั้งค่า Function directory
[functions]
  directory = "netlify/functions"

# ตั้งค่า Headers สำหรับ CORS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "POST, OPTIONS, GET"

# ตั้งค่า Redirects สำหรับ API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
